// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// CursorPage カーソルページネーションの共通部分。
//
// 一覧エンドポイントは、このスキーマの `items` を具体的な要素型に
// 差し替えた `XxxPage` を定義し、それを `Envelope` の `data` に入れます。
// **オフセット方式（`page` / `per_page`）は提供しません。**
// Firestore の `Offset()` は読み飛ばした分も課金対象になるためです。
type CursorPage struct {
	// Items このページの要素。
	Items []interface{} `json:"items"`

	// NextCursor 次ページを取得するための不透明なカーソル。
	// 末尾に達している場合は `null` です。
	// 値の形式は保証しません。そのまま `cursor` クエリに渡してください。
	//
	//
	// Examples: eyJ1cGRhdGVkQXQiOiIyMDI2LTA3LTI4In0
	NextCursor *NextCursor `json:"next_cursor"`
}

// Envelope 全応答に共通する封筒。**`data` と `error` はどちらか一方が必ず `null`** です。
//
// 個別の応答は、このスキーマの `data` を具体的な型に差し替えた
// `XxxEnvelope` として定義します（例: `HealthEnvelope`）。
type Envelope struct {
	// Data 成功時のペイロード。失敗時は `null`。
	Data interface{} `json:"data"`

	// Error 失敗時の内容。成功時は `null`。
	Error *Error `json:"error"`
}

// Error 失敗の内容。`code` で分岐し、`message` はそのまま画面に表示します。
type Error struct {
	// Code 機械可読なエラーコード（SCREAMING_SNAKE_CASE）。
	//
	// Examples: NOTE_NOT_FOUND
	Code string `json:"code"`

	// Message 利用者にそのまま見せる日本語の説明。内部情報を含めません。
	//
	// Examples: ノートが見つかりません。一覧から選び直してください。
	Message string `json:"message"`
}

// ErrorEnvelope 失敗時の封筒。`data` は常に `null`。
type ErrorEnvelope struct {
	// Data 失敗時は常に `null`。
	Data any `json:"data"`

	// Error 失敗の内容。`code` で分岐し、`message` はそのまま画面に表示します。
	Error Error `json:"error"`
}

// Health 死活確認の結果。
type Health struct {
	// Revision デプロイの識別子（Cloud Run の `K_REVISION`）。
	// 不明な場合は `unknown` を返します。
	//
	//
	// Examples: octant-00001-abc
	Revision string `json:"revision"`

	// Status 稼働状態。稼働中は常に `ok`。
	Status HealthStatus `json:"status"`
}

// HealthStatus 稼働状態。稼働中は常に `ok`。
type HealthStatus string

// HealthEnvelope `GET /health` の成功応答。
type HealthEnvelope struct {
	// Data 死活確認の結果。
	Data Health `json:"data"`

	// Error 成功時は常に `null`。
	Error any `json:"error"`
}

// NextCursor 次ページを取得するための不透明なカーソル。
// 末尾に達している場合は `null` です。
// 値の形式は保証しません。そのまま `cursor` クエリに渡してください。
//
// Examples: eyJ1cGRhdGVkQXQiOiIyMDI2LTA3LTI4In0
type NextCursor = string

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int32

// BadRequest 失敗時の封筒。`data` は常に `null`。
type BadRequest = ErrorEnvelope

// Forbidden 失敗時の封筒。`data` は常に `null`。
type Forbidden = ErrorEnvelope

// InternalServerError 失敗時の封筒。`data` は常に `null`。
type InternalServerError = ErrorEnvelope

// MethodNotAllowed 失敗時の封筒。`data` は常に `null`。
type MethodNotAllowed = ErrorEnvelope

// NotFound 失敗時の封筒。`data` は常に `null`。
type NotFound = ErrorEnvelope

// TooManyRequests 失敗時の封筒。`data` は常に `null`。
type TooManyRequests = ErrorEnvelope

// Unauthorized 失敗時の封筒。`data` は常に `null`。
type Unauthorized = ErrorEnvelope

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth 死活確認
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// HeadHealth 死活確認（ボディなし）
	// (HEAD /health)
	HeadHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetHealth 死活確認
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// HeadHealth 死活確認（ボディなし）
// (HEAD /health)
func (_ Unimplemented) HeadHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HeadHealth operation middleware
func (siw *ServerInterfaceWrapper) HeadHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HeadHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Head(options.BaseURL+"/health", wrapper.HeadHealth)
	})

	return r
}
